### ISSUE TITLE
public/index.html file was missing

### ISSUE THREAD

**Issue by kittu1840** [petr166/mean-chat-app#1]
total application has didnt have any dobuts.but, the index.html file was missing dude.could you please add it?

**Comment by petr166** [comment]
I am using the `/public` directory for the built app. To run it in *dev* you need 3 processes, in order:

- mongo db local server (you can also connect to external, add link to `config/database.js`)
    - you need to have mongodb installed, go [here](https://www.mongodb.com/download-center#community)
    - terminal > `mongod`
- nodejs api server
    - terminal > cd into project directory > `npm start`
- angular dev server
    - terminal > cd into project directory > cd angular-src > `npm start`

Now you can go to http://localhost:4200 on ur browser to check the app ;)

> when the angular app gets built, its static files are stored in the `/public` directory to be served by the node server (so I don't have to use another nginx etc.)

**Comment by kittu1840** [comment]
great!! resolved
