### ISSUE TITLE
Unable to get started with index.html

### ISSUE THREAD

**Issue by niroshan123** [petr166/mean-chat-app#11]
Since in the repo there is no public file. Instead of that there is an angular-src and front end not appearing when i download the zip and npm install

**Comment by petr166** [comment]
Please follow the instructions in README to run the project

**Comment by sumanks3** [comment]
there is no index.html 
Error: ENOENT: no such file or directory, stat 'C:\Users\suma\Desktop\mean-chat-app-master\mean-chat-app-master\public\index.html'
