### ISSUE TITLE
 Connection closed before receiving a handshake response

### ISSUE THREAD

**Issue by rajpavan** [petr166/mean-chat-app#2]
WebSocket connection to 'ws://localhost:8080/socket.io/?EIO=3&transport=websocket' failed: Connection closed before receiving a handshake response

**Comment by seersol92** [comment]
please check this http://prntscr.com/j6rwxn

**Comment by petr166** [comment]
Hi, sorry for late response. Try pulling the latest version (i think i fixed all the issues)
