### ISSUE TITLE
MongoDb connectivity procedure

### ISSUE THREAD

**Issue by Chandrashekhar-N** [petr166/mean-chat-app#29]
@petr166 --It's "not issue" actually, for beginners who don't know how to use MongoDb or how to run project which uses MongoDb like your project it'll be helpful if you provide "procedure to connect with MongoDb" step by step in "README" file. please add procedure that where we need make file changes everything. i don't know how to communicate with you so, i raised this issue. hope you understand this small problem.

**Comment by petr166** [comment]
Mongo connection is done using [MONGO_HOST](https://github.com/petr166/mean-chat-app/blob/master/.env.example#L3) env variable. If the issue you're referring to is installing and setting up mongo locally, that is outside the scope of this project and can easily be found through a google search.
If you thought of something else, please reopen the issue and describe it further 😊
