### ISSUE TITLE
Demo link does not work

### ISSUE THREAD

**Issue by 1Map** [petr166/mean-chat-app#4]
Your demo link does not work

**Comment by petr166** [comment]
yes, i'm moving my hosting space, should be up again soon

**Comment by bsKannan** [comment]
your file not working after clone and run,it should some cors error and the host number is also changed

**Comment by petr166** [comment]
@bsKannan please be more specific

**Comment by bsKannan** [comment]
please clone and run your repo and it throws error that 8080 port and also throws cors error

**Comment by petr166** [comment]
@bsKannan it would help if you write the error and/or add some screenshots, for me to be able to figure it out

**Comment by delian1986** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/22419550/55213080-dfcdef80-51fa-11e9-942e-17e745d42629.png)

**Comment by petr166** [comment]
@delian1986 did you start all the processes including the backend api?

**Comment by petr166** [comment]
inactive

**Comment by 1Map** [comment]
@petr166  Please do not close this threat as your demo page still does not work.

http://petrub.com/chat-app

**Comment by petr166** [comment]
@1Map true that :)

**Comment by petr166** [comment]
demo is back up
