### ISSUE TITLE
Angular-src can't compile

### ISSUE THREAD

**Issue by antalmate12** [petr166/mean-chat-app#5]
Hello.
Did everything as you wrote, but when I'm in the angular-src and use the command npm start, I get this: webpack: Failed to compile. and a bunch of "Module build failed"s., seen below in the log.txt file.
[log.txt](https://github.com/petr166/mean-chat-app/files/2673030/log.txt)
Any idea how should I fix it?

**Comment by petr166** [comment]
did you install the packages? try 
```bash  
rm -rf node_modules && npm install && npm start
```  
in `angular-src` directory
