### ISSUE TITLE
http://localhost:8000/api/users/register net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by ManishDhawal** [petr166/mean-chat-app#6]
how to resolve this issue?

**Comment by petr166** [comment]
did you run the backend api? please follow the instructions in README and try again

**Comment by ldilshan** [comment]
I ran the backend also. How to fix it?

**Comment by AshayTikekar** [comment]
> I ran the backend also. How to fix it?

@ldilshan @ManishDhawal  Kindly try the following before running `npm run dev`

- `export ROOT = "/api"`

- change PORT = 8000 in config/index.js so that it matches on the client side

This is should solve the issue. I have addressed the same in PR  #8 

Regards,
Ashay

**Comment by ldilshan** [comment]
Thanks Ashay. I have already done like this.sorry for the late reply.

**Comment by AshayTikekar** [comment]
@ldilshan 

You can close the issue if it's solved.

Happy Coding!

Regards,
Ashay
